# 注意使用了 自定义配置文件路径时，
# spring boot 将不会去找 application-{profile}.yaml 文件

common:
  config: common-config-value

---

spring:
  profiles: prod

project:
  jdbc: prod-jdbc

---
spring:
  profiles: test

project:
  jdbc: test-jdbc