spring:
  application:
    name: spring-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  sensitive-headers: Cookie
  routes:
    # 简单路由：path + url
    # 测试：http://localhost:9000/163
    route163:
      path: /163
      url: http://www.163.com
    # 简单路由，省略path，serviceId 将作为默认path
    # 测试：http://localhost:9000/baidu
    baidu:
      url: http://www.baidu.com
    # forward : 直接的跳向目标地址，响应不经过gateway
    # 测试：http://localhost:9000/fd/
    fd:
      url: forward:/fd
#    #Ribbon 路由：serviceId + path
#    #测试：http://localhost:9000/invoker/call
#    invoker-service:
#      serviceId: spring-zuul-invoker
#      path: /invoker/**
#    # Ribbon 路由，省略显示配置 serviceId
#    # 测试：http://localhost:9000/service/hello/jim
#    spring-zuul-service:
#      path: /service/**
management:
  security:
    enabled: false
