spring:
  application:
    name: spring-stream-producer
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.1.25
          zkNodes: 192.168.1.25
  # rabbitmq 默认
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/