spring:
  application:
    name: lb-invoker-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: org.orh.spring.cloud.ch108.MyRule