server:
  port: 10000
spring:
  application:
    name: eu-bus
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1
          zkNodes: 127.0.0.1
    bus:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false
